# Generated by Django 2.2 on 2021-03-04 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210304_1246'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailqueue',
            table='email_queue',
        ),
    ]
