# Generated by Django 2.2 on 2021-03-04 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210304_1248'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailqueue',
            table='core_email_queue',
        ),
    ]
