# Generated by Django 2.2 on 2021-03-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210304_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('error', 'Error'), ('cancel', 'Cancelado')], default='pending', max_length=255),
        ),
    ]
