# Generated by Django 2.2 on 2021-03-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210304_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailqueue',
            name='email_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
