# Generated by Django 2.2 on 2021-03-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_emailqueue_email_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailqueue',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
