# Generated by Django 2.2 on 2021-03-08 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210308_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Template'),
        ),
        migrations.AddField(
            model_name='template',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
