# Generated by Django 2.2.19 on 2021-03-19 09:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailqueue',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank='True', null='True'),
            preserve_default='True',
        ),
    ]
