# Generated by Django 2.2.19 on 2021-03-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_emailqueue_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='sender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
